Document: desigle
Title: Debian desigle Manual
Author: <insert document author here>
Abstract: This manual describes what desigle is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/desigle/desigle.sgml.gz

Format: postscript
Files: /usr/share/doc/desigle/desigle.ps.gz

Format: text
Files: /usr/share/doc/desigle/desigle.text.gz

Format: HTML
Index: /usr/share/doc/desigle/html/index.html
Files: /usr/share/doc/desigle/html/*.html
